version: '3.8'

services:
  db:
    image: postgres:13
    env_file: ./docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    env_file: ./docker.env
    volumes:
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app:/app/backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=/api/
    depends_on:
      - backend

volumes:
  postgres_data: